server:
  port: 8080
  servlet:
    context-path: /

  ####Jetty specific properties########
  jetty:
    # Number of acceptor threads to use.
    # acceptors: 10

    # Maximum size in bytes of the HTTP post or put content.
    max-http-form-post-size: 1000000000

    # Number of selector threads to use.
    # selectors:


eforms:
  sdk:
    # Path to eForms SDK
    path: eforms-sdk

    # Comma-separated list of the supported major versions of eForms SDK
    versions: 1.6


proxy:
  ### Security: use a command line parameter for security related data
  ### Example -Dproxy.url=ENVIRONMENT_VARIABLE_VALUE_HERE
  # url: http://user:pass@hostname:port

client:
  cvs:
    url: "https://cvs.ted.europa.eu"
    ### Security: use a command line parameter for security related data
    ### Example -Dclient.cvs.apiKey=ENVIRONMENT_VARIABLE_VALUE_HERE
    apiKey: "YOUR_API_KEY"
