server:
  port: 8080
  servlet:
    context-path: /

  ####Jetty specific properties########
  jetty:
    # Number of acceptor threads to use.
    # acceptors: 10

    # Maximum size in bytes of the HTTP post or put content.
    max-http-form-post-size: 1000000000

    # Number of selector threads to use.
    # selectors:


eforms:
  sdk:
    # Path to eForms SDK
    path: eforms-sdks

    # Comma-separated list of the supported major versions of eForms SDK
    versions: 1.0,1.1,1.2,1.3,1.4,1.5


proxy:
  hostname: "PROXY_HOSTNAME"
  port: 8012
  username: "YOUR_USERNAME"
  password: "YOUR_PASSWORD"


client:
  cvs:
    url: "https://cvs.ted.europa.eu"
    api-key: "YOUR_API_KEY"
